# This is the name of the workflow
name: Build Desktop Release

# This is the trigger
on:
  release:
    types: [published]

# This is the new section that defines the work to be done
jobs:
  build:
    # This strategy block tells GitHub to run the same set of steps
    # on three different operating systems in parallel.
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    # This sets the operating system for the current job run
    runs-on: ${{ matrix.os }}

    # These are the individual steps the virtual machine will execute
    steps:
      # Step 1: Check out the code from your repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up the Java JDK (version 17)
      # This is crucial for the jpackage tool to work correctly.
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt' # Use the Adoptium JDK, a reliable choice

